# Generated by Django 4.1.7 on 2023-09-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
        ('base', '0003_user_avatar'),
    ]

    operations = [
    ]
